"""
Services module for ChemoCare AI.
"""
from app.services.gemini_ai import (
    generate_protocol,
    calculate_dose_with_ai,
    check_drug_interactions,
    analyze_labs_for_treatment,
    analyze_patient_symptoms,
    get_treatment_recommendations,
    ProtocolGenerationResult,
    DoseCalculationResult,
    DrugInteractionResult,
    LabAnalysisResult,
    SymptomAnalysisResult,
)
from app.services.document_extraction import (
    extract_from_image,
    extract_from_text,
    extract_and_map_document,
    batch_extract_documents,
    DocumentExtractionResult,
    LabPanelMapping,
)
from app.services.push_notifications import (
    send_push_notification,
    send_batch_notifications,
    notify_user,
    notify_appointment_reminder,
    notify_treatment_due,
    notify_protocol_approval_required,
    notify_protocol_approved,
    notify_vitals_alert,
    notify_medication_due,
    PushNotification,
    PushNotificationResult,
    BatchPushResult,
)
from app.services.scheduling import (
    schedule_appointment,
    schedule_treatment_cycles,
    reschedule_appointment,
    cancel_appointment,
    get_available_slots,
    get_chair_availability,
    get_daily_schedule,
    get_patient_schedule,
    schedule_reminders,
    TimeSlot,
    SchedulingResult,
    TreatmentScheduleResult,
    ChairAvailability,
    DailySchedule,
)

__all__ = [
    # Gemini AI
    "generate_protocol",
    "calculate_dose_with_ai",
    "check_drug_interactions",
    "analyze_labs_for_treatment",
    "analyze_patient_symptoms",
    "get_treatment_recommendations",
    "ProtocolGenerationResult",
    "DoseCalculationResult",
    "DrugInteractionResult",
    "LabAnalysisResult",
    "SymptomAnalysisResult",
    # Document extraction
    "extract_from_image",
    "extract_from_text",
    "extract_and_map_document",
    "batch_extract_documents",
    "DocumentExtractionResult",
    "LabPanelMapping",
    # Push notifications
    "send_push_notification",
    "send_batch_notifications",
    "notify_user",
    "notify_appointment_reminder",
    "notify_treatment_due",
    "notify_protocol_approval_required",
    "notify_protocol_approved",
    "notify_vitals_alert",
    "notify_medication_due",
    "PushNotification",
    "PushNotificationResult",
    "BatchPushResult",
    # Scheduling
    "schedule_appointment",
    "schedule_treatment_cycles",
    "reschedule_appointment",
    "cancel_appointment",
    "get_available_slots",
    "get_chair_availability",
    "get_daily_schedule",
    "get_patient_schedule",
    "schedule_reminders",
    "TimeSlot",
    "SchedulingResult",
    "TreatmentScheduleResult",
    "ChairAvailability",
    "DailySchedule",
]
